### ISSUE TITLE
Add the mission patch to the documentation

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/floripasat2-doc#18]
Add a description about the mission patch (maybe in the introduction chapter).

**Comment by YanAzer** [comment]
I think we can close this issue @mgm8

**Comment by mgm8** [comment]
I think we should add a brief explanation about the patch (the main elements, colors, the background, etc.).

**Comment by YanAzer** [comment]
@mgm8 leave that to me, is gonna be a brief explanation since the patch can (and it will) change over the time.
